name: Update Product Formula in Tap
# This workflow will automatically update our product formulae on the release of
# new versions
on:
  repository_dispatch:
    types: [version-updated]

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@2.3.4
        with:
          fetch-depth: 0
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      -
        name: Build formula_templater CLI
        run: |
          cd util/formula_templater && go build
      -
        name: Generate new formula
        if: ${{ github.event.client_payload.cask == 'false' }}
        run: |
          ./util/formula_templater/formula_templater ${{github.event.client_payload.name}} ${{github.event.client_payload.version}} ./util/formula_templater/config.hcl > ./Formula/${{github.event.client_payload.name}}.rb
      -
        name: Generate new formula
        if: ${{ github.event.client_payload.cask == 'true' }}
        run: |
          ./util/formula_templater/formula_templater ${{github.event.client_payload.name}} ${{github.event.client_payload.version}} ./util/formula_templater/config.hcl > ./Casks/${{github.event.client_payload.name}}.rb
      -
        name: Commit new formula
        if: ${{ github.event.client_payload.cask == 'false' }}
        run: |
          git add ./Formula/${{github.event.client_payload.name}}.rb
          git commit -m'${{github.event.client_payload.name}} ${{github.event.client_payload.version}}'
          git push
      -
        name: Commit new formula
        if: ${{ github.event.client_payload.cask == 'true' }}
        run: |
          git add ./Casks/${{github.event.client_payload.name}}.rb
          git commit -m'${{github.event.client_payload.name}} ${{github.event.client_payload.version}}'
          git push
