name: Update Product Formula in Tap
# This workflow will automatically update our product formulae on the release of
# new versions
on:
  repository_dispatch:
    types: [version-updated]

jobs:
  formula-bump-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: kpenfound fork of dawidd6 Homebrew bump formula
        uses: kpenfound/action-homebrew-bump-formula@v3.2.3
        with:
          token: ${{secrets.HOMEBREW_TOKEN}}
          tap: hashicorp/homebrew-tap
          formula: ${{github.event.client_payload.name}}
          tag: ${{github.event.client_payload.version}}
      - name: kpenfound fork of Merge pull requests
        uses: kpenfound/automerge-action@v0.9.0
        env:
          GITHUB_TOKEN: "${{secrets.HOMEBREW_TOKEN}}"
          MERGE_LABELS: ""
          MERGE_FILTER_AUTHOR: "hc-espd-packager"
